// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMvrv4H5dvET-4ESg_ArfidVPMjkWmnA4',
    appId: '1:422488101360:web:5f6538416dccb279ad0d35',
    messagingSenderId: '422488101360',
    projectId: 'kalan-9a684',
    authDomain: 'kalan-9a684.firebaseapp.com',
    storageBucket: 'kalan-9a684.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_bJZkL97sLDIFbPsJPjrKUQbNzRMaMVI',
    appId: '1:422488101360:android:6cec6d6fcac7e34bad0d35',
    messagingSenderId: '422488101360',
    projectId: 'kalan-9a684',
    storageBucket: 'kalan-9a684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmsJv1e8KBNLAf0pPV4QJLI7_ir0SZ7Zs',
    appId: '1:422488101360:ios:b3f0698b16c75814ad0d35',
    messagingSenderId: '422488101360',
    projectId: 'kalan-9a684',
    storageBucket: 'kalan-9a684.appspot.com',
    iosBundleId: 'com.example.gdsc1Win',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmsJv1e8KBNLAf0pPV4QJLI7_ir0SZ7Zs',
    appId: '1:422488101360:ios:27e564ee3afb67b0ad0d35',
    messagingSenderId: '422488101360',
    projectId: 'kalan-9a684',
    storageBucket: 'kalan-9a684.appspot.com',
    iosBundleId: 'com.example.gdsc1Win.RunnerTests',
  );
}
